name: Fix start URLs
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  fix:
    if: !contains(github.event.head_commit.message, 'Canonical URL fix')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: find . -type f -name '*.html' -exec sed -i 's#https://eminordu7.github.io/rechner-schweiz/index.html#https://eminordu7.github.io/rechner-schweiz#g' {} +
      - run: git config user.name 'github-actions[bot]'
      - run: git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: git add .
      - run: git commit -m 'Canonical URL fix'
      - run: git push